### ISSUE TITLE
Error: There is not any matching panel for the given interval

### ISSUE THREAD

**Issue by mhaiyue** [cotsapaslab/jlim#6]
Hi,

I get the "There is not any matching panel for the given interval" error when I set a larger --window-size, e.g. --window-size=2mb.

The [pre-processed reference genotype panels](https://github.com/cotsapaslab/jlim#installation) are split into small files by chromosome and position ranges (e.g. chr1.56839599_60312420.txt.gz), so here comes the error according to [code](https://github.com/cotsapaslab/jlim/blob/3cc3258b68a39d943a4474a25f9329e0dfbe26f2/jlimR/R/jlimCmd.R#L629): 

If the position of the  index-snp is near the start(or end) bp, or the value of "--window-size"  argument is too large to fit into end bp - start bp, we will get this error.

Any would be much appreciated!

**Comment by Asppagh** [comment]
Hi,
The package tries to find the right reference panel file based on the input  index-sap and also window-size  parameters. having a very large window size could possibly cause that error as the panels are on average 2M bp wide. Generally we do not recommend such a large window size. If you still would like to go ahead with that setting, instead a of specifying ref-panel directory you should manually select the reference panels file that fits your input parameters and assigned it using --ref-ld parameter.
Let me know if that helps to resolve your error.

**Comment by sgchun** [comment]
Hi, 

Can I ask you why you need such a wide window size? This will cause all colocalization tests (including JLIM) to be more likely to classify the locus as driven by distinct causative variants (H2 in the case of JLIM). We do not recommend such a wide window size because of the polygenic nature of most complex traits. If you are perhaps setting this up for benchmark comparison, I do not think it's a fair comparison. 
Hope this helps.
 
Sung
